version: "3.8"

services:
  server:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
    image: mongo:latest
  client:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    volumes:
      - type: volume
        source: static
        target: /static
    depends_on:
      - server
  nginx:
    image: nginx:latest
    volumes:
      - type: volume
        source: static
        target: /usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - client
volumes:
  static:
